{
 "title": "👨‍🚒 Endpoints & Network",
 "description": "Watch endpoints health and some info about subgraphs",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Epoch & Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Epoch Progress Tracker",
   "type": "timeseries",
   "description": "Epoch progress and frames",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(graph_prom_block{instance=\"$instance\",job=\"$job\"}) - (graph_prom_epoch_start_block{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "Epoch progress in blocks:"
    },
    {
     "expr": "(graph_prom_epoch_end_block{instance=\"GM1\",job=\"exporter-graph-custom\"}) - (graph_prom_block{instance=\"GM1\",job=\"exporter-graph-custom\"})",
     "legendFormat": "Blocks till end of epoch:"
    }
   ]
  },
  {
   "title": "Blocks In Epoch",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(graph_prom_epoch_end_block{instance=\"$instance\",job=\"$job\"}) - (graph_prom_epoch_start_block{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "Blocks till epoch end:"
    }
   ]
  },
  {
   "title": "Endpoints Flow For Alerts",
   "type": "timeseries",
   "description": "INDEXER_AGEN_EPOCH_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(graph_prom_block{instance=\"$instance\",job=\"$job\"}[600s])) / 100 ",
     "legendFormat": "Network:"
    },
    {
     "expr": "sum(increase(graph_prom_oracle_block{instance=\"GM1\",job=\"exporter-graph-custom\"}[600s])) / 100",
     "legendFormat": "Oracle:"
    }
   ]
  },
  {
   "title": "BLOCK",
   "type": "stat",
   "description": "INDEXER_AGEN_EPOCH_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_block{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "NETWORK"
    },
    {
     "expr": "graph_prom_oracle_block{instance=\"GM1\",job=\"exporter-graph-custom\"}",
     "legendFormat": "ORACLE"
    }
   ]
  },
  {
   "title": "EPOCH",
   "type": "stat",
   "description": "INDEXER_AGEN_EPOCH_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_epoch{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "NETWORK"
    },
    {
     "expr": "graph_prom_oracle_epoch{instance=\"GM1\",job=\"exporter-graph-custom\"}",
     "legendFormat": "ORACLE"
    },
    {
     "expr": "graph_prom_juan_oracle_epoch{instance=\"the_graph_mip\",job=\"endpoints-exporter\"}",
     "legendFormat": "JUAN"
    }
   ]
  },
  {
   "title": "Tip flow",
   "type": "timeseries",
   "description": "INDEXER_AGEN_EPOCH_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "graph_prom_block{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Network:"
    },
    {
     "expr": "graph_prom_oracle_block{instance=\"GM1\",job=\"exporter-graph-custom\"}",
     "legendFormat": "Oracle:"
    }
   ]
  },
  {
   "title": "Epoch switch",
   "type": "timeseries",
   "description": "INDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "graph_prom_epoch{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Network:"
    },
    {
     "expr": "graph_prom_oracle_epoch{instance=\"GM1\",job=\"exporter-graph-custom\"}",
     "legendFormat": "Oracle:"
    }
   ]
  },
  { "title": "Subgraphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Currently Deprecated Subgraphs",
   "type": "stat",
   "description": "INDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT\n\nIf any subgraph become deprecated we will know",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_deprecated_subs{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Active Subgraphs",
   "type": "stat",
   "description": "INDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT\n\nTotal subgraphs allocated",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_active_subs{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subgraph Age",
   "type": "timeseries",
   "description": "Age of subgraphs in blocks\nINDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "graph_prom_alloc_ages{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ name }} {{ id }}"
    }
   ]
  },
  {
   "title": "Subgraph Age",
   "type": "bargauge",
   "description": "Age of subgraphs in blocks\nINDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_alloc_ages{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ name }} {{ id }}"
    }
   ]
  },
  {
   "title": "Active Subgraphs",
   "type": "timeseries",
   "description": "INDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "graph_prom_active_subs{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Active subgraphs:"
    }
   ]
  },
  {
   "title": "Currently Depricated Subgraphs",
   "type": "timeseries",
   "description": "INDEXER_AGEN_NETWORK_SUBGRAPH_ENDPOINT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "graph_prom_deprecated_subs{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Lost subgraphs:"
    }
   ]
  },
  { "title": "System & SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "SSL EXPIRATION FRAME IN DAYS",
   "type": "timeseries",
   "description": "HTTPS://INDEXER.URL [ set up in config ]",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "graph_prom_ssl_checks{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "SSL VALID UNTIL",
   "type": "stat",
   "description": "HTTPS://INDEXER.URL [ set up in config ]",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_ssl_checks{instance=\"$instance\",job=\"$job\",id=\"valid_till\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Exporter Errors Rate [ 5m ]",
   "type": "timeseries",
   "description": "Any network error will increment this value by one. Can be used for alerting ( not recommended )",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "increase(graph_prom_check_errors{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "ERRORS COUNTER"
    }
   ]
  },
  {
   "title": "Exported Endpoint Response Code",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graph_prom_endpoint_healthcheck{instance=\"GM1\",job=\"exporter-graph-custom\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}